### ISSUE TITLE
add the ability to use placeholders in messages.

### ISSUE THREAD

**Issue by cole3050** [mrgeneralq/sleep-most#156]
add the ability to use placeholders in messages.

Example "&aGood morning, %medievalfactions_faction_prefix%!"

Being able to use other plugins that support placeholder API will allow the messages to fit the servers better.

**Comment by mrgeneralq** [comment]
Hello @cole3050 

We will investigate if that is going to be possible.

Kind regards

Quinten

**Comment by mrgeneralq** [comment]
Hello @cole3050 

We have been investigating the options, however I'm afraid that due to the requirements of placeholder API always requiring a player to set placeholders which in many cases, the message is not personalized.

I'm afraid that for now we have to reject this request.
My apologies for this inconvenience.

Kind regards

Quinten
